services:
  frontend-prod:
    container_name: eg-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://eg-backend-prod:5000
    depends_on:
      - backend-prod

  backend-prod:
    container_name: eg-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=http://localhost
      - DOCS_URL=http://localhost:3000
      - PORT=5000
      - DB_CONNECTION_STRING=mongodb://admin:admin@eg-db-prod:27017/myapp?authSource=admin
      - PASSWORD_SALT=acfe4d0752b66cedfb5ab6d23e47621f
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=1h
    depends_on:
      - db-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  docs-prod:
    container_name: eg-docs-prod
    build:
      context: ./docs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend-prod

  db-prod:
    image: mongo:latest
    container_name: eg-db-prod
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          "db.runCommand('ping').ok",
          "localhost:27017/myapp",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
